name: Solar Challenge Week 0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installation (optional)
      run: |
        python -c "import numpy, pandas, pytz, six; print('Packages installed successfully')"

        
    - name: Run Tests
      run: |
        pytest
